const sectors: string[] = [
  "Gauthier",
  "Chimicolor",
  "Maârif",
  "Racine",
  "Palmier",
  "Bourgogne",
  "Beauséjour",
  "Anfa",
  "Ain Diab",
  "Californie",
  "2 Mars",
  "Riviera",
  "Oasis",
  "Ain Sebaâ",
  "Sidi Maârouf",
  "Zounbir",
  "Belvédère ",
  "Derb Sultan",
  "Hay El Hassani",
  "Inara",
  "Oulfa",
  "Oasis",
  "Les Roches Noires",
  "Gironde",
  "Dar Bouazza",
  "Habous",
  "Al Fida",
  "Bourmazil",
  "Derb Ghallef",
  "Derb Omar",
  "Hay Mansour",
  "Hay Moulay Rachid",
  "Hermitage",
  "Lissasfa",
  "Longchamps",
  "Mers Sultan",
  "Riviera",
  "Rhama",
  "Toïd",
  "Sbata",
  "Sidi Beylout",
  "Sidi Bernoussi",
  "Sidi Moumen",
  "Sidi Othmane",
  "Val Fleuri",
].sort();

export default sectors;
